# Generated by Django 2.0.7 on 2020-07-16 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.IntegerField(unique=True)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Exercise1', models.CharField(max_length=10)),
                ('ML_Course', models.CharField(max_length=10)),
                ('ML_Project', models.CharField(max_length=10)),
                ('Exercise2', models.CharField(max_length=10)),
                ('DSA_Learning', models.CharField(max_length=10)),
                ('DSA_Coding', models.CharField(max_length=10)),
                ('Walk', models.CharField(max_length=10)),
                ('Problem_Solving', models.CharField(max_length=10)),
            ],
        ),
    ]
