# Generated by Django 2.2.13 on 2020-07-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Day',
            field=models.IntegerField(),
        ),
    ]
