# Generated by Django 2.2.13 on 2020-07-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScheduleBook', '0002_auto_20200717_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='Day',
            field=models.IntegerField(unique=True),
        ),
    ]
